### ISSUE TITLE
Progress of this project?

### ISSUE THREAD

**Issue by almothafar** [zxing-js/browser#10]
As I can see this project got almost no changes in 2 years, yet you deprecated `BrowserBarcodeReader` in favor of this "when" it is ready
https://github.com/zxing-js/library/issues/89

So is this project still active? if not or you need more time, can you remove the deprecation message then?

**Comment by odahcam** [comment]
This is in fact progressing really well, I just finished enabling E2E tests in the browser layer of the library (it was the only requirement/blocking issue for this project to happen). Now I just need to migrate the source of the browser layer from there to this repo. Anyone can do that via a Pull Request by the way. 

My plan was to implement some meaningful E2E tests there before in fact making the migration, just to give users time to migrate. I'm not really interested in removing the deprecation tags as I want users to know that the classes won't be available in any time, the browser layer inside the library is entirely deprecated and I just didn't delete that because there's no alternative yet.

So, for any potential contributors here, please think first of copy pasting the code and tests from the library to this repo before spend hours erasing warnings that does nothing for the library itself.

**Comment by odahcam** [comment]
Here's progress: https://github.com/zxing-js/browser/releases/tag/v0.0.1-preview.1

I think we can close this now.

**Comment by greenyleaf** [comment]
`BrowserBarcodeReader` is still not in the browser package.
